# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import CopyListwithRandomPointer as module_0


#@pytest.mark.xfail(strict=True)
def test_case_0():#FAILED: 'bool' object has no attribute 'val'
    bool_0 = True
    module_0.copyRandomList(bool_0)


def test_case_1():#PASSED
    none_type_0 = None
    var_0 = module_0.copyRandomList(none_type_0)


def test_case_2():#PASSED
    node_0 = module_0.Node()
    assert node_0.val == 0
