# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import brute_force as module_0


def test_case_0(): # PASSED
    solution_0 = module_0.Solution()


def test_case_1(): # PASSED
    int_0 = -2055
    list_0 = [int_0]
    int_1 = 3758
    solution_0 = module_0.Solution()
    var_0 = solution_0.findMaxAverage(list_0, int_1)
    assert var_0 == pytest.approx(-2055.0, abs=0.01, rel=0.01)


def test_case_2(): # PASSED
    solution_0 = module_0.Solution()
    int_0 = -2098
    list_0 = [int_0]
    solution_1 = module_0.Solution()
    bool_0 = True
    var_0 = solution_1.findMaxAverage(list_0, bool_0)
    assert var_0 == pytest.approx(-2098.0, abs=0.01, rel=0.01)
