# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import ReverseLinkedList as module_0


def test_case_0():#PASSED
    list_node_0 = module_0.ListNode()
    assert list_node_0.val == 0
    list_node_1 = module_0.reverseList(list_node_0)
    assert (
        f"{type(list_node_1).__module__}.{type(list_node_1).__qualname__}"
        == "ReverseLinkedList.ListNode"
    )
    assert list_node_1.val == 0
    assert list_node_1.next is None
    list_node_2 = module_0.reverseList(list_node_1)
    assert (
        f"{type(list_node_2).__module__}.{type(list_node_2).__qualname__}"
        == "ReverseLinkedList.ListNode"
    )
    assert list_node_2.val == 0
    assert list_node_2.next is None


def test_case_1():#PASSED
    none_type_0 = None
    list_node_0 = module_0.reverseList(none_type_0)
    list_node_1 = module_0.ListNode(next=none_type_0)
    assert list_node_1.val == 0


def test_case_2():#PASSED
    list_node_0 = module_0.ListNode()
    assert list_node_0.val == 0
    list_node_1 = module_0.ListNode(list_node_0)


#@pytest.mark.xfail(strict=True)
def test_case_3():#FAILED: 'bytes' object has no attribute 'next'
    bytes_0 = b"\xcd{\xaf8Gz\xe6p'\xb4F\xdb}"
    list_node_0 = module_0.ListNode()
    assert list_node_0.val == 0
    list_node_1 = module_0.ListNode(next=bytes_0)
    assert list_node_1.val == 0
    list_node_2 = module_0.ListNode()
    assert list_node_2.val == 0
    list_node_3 = module_0.ListNode(list_node_2)
    int_0 = 3539
    list_node_4 = module_0.ListNode()
    assert list_node_4.val == 0
    list_node_5 = module_0.ListNode(int_0)
    list_node_6 = module_0.ListNode(next=bytes_0)
    assert list_node_6.val == 0
    list_node_7 = module_0.ListNode(list_node_0, list_node_4)
    module_0.reverseList(list_node_6)
