# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test as module_0


# @pytest.mark.xfail(strict=True)
def test_case_0(): # FAILED - AttributeError: 'Solution' object has no attribute 'right'
    solution_0 = module_0.Solution()
    none_type_0 = None
    var_0 = solution_0.invertTree(none_type_0)
    solution_0.invertTree(solution_0)


# @pytest.mark.xfail(strict=True) 
def test_case_1(): # FAILED - TypeError: test.Solution() argument after * must be an iterable, not TreeNode
    tree_node_0 = module_0.TreeNode()
    assert tree_node_0.val == 0
    solution_0 = module_0.Solution()
    module_0.Solution(*tree_node_0)
