# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P1 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    solution_0 = module_0.Solution()
    str_0 = "#]*N"
    str_1 = 'e?PF|lQl\x0bARN"~Ou[\\y'
    int_0 = solution_0.numJewelsInStones(str_0, str_1)
    assert int_0 == 1
    str_2 = "\n*s\\n}*[)v"
    str_3 = "c"
    str_4 = ':{[|IIlhL"{G\t~2'
    dict_0 = {str_2: int_0, str_3: str_0, str_4: str_1}
    module_0.Solution(**dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    solution_0 = module_0.Solution()
    str_0 = '9DS"Z? 4+J~zNlN~\rm?.'
    solution_0.numJewelsInStones(solution_0, str_0)
