# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test as module_0


def test_case_0(): # PASSED
    solution_0 = module_0.Solution()
    none_type_0 = None
    int_0 = solution_0.diameterOfBinaryTree(none_type_0)
    assert int_0 == 0


# @pytest.mark.xfail(strict=True)
def test_case_1(): # FAILED - test_test.py::test_case_1 - AttributeError: 'Solution' object has no attribute 'left'
    dict_0 = {}
    solution_0 = module_0.Solution(**dict_0)
    solution_1 = module_0.Solution()
    solution_1.diameterOfBinaryTree(solution_0)


def test_case_2(): # PASSED
    list_0 = []
    tree_node_0 = module_0.TreeNode(left=list_0)
    assert tree_node_0.val == 0
