# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import cod as module_0

#https://github.com/gahogg/Leetcode-Solutions/blob/main/Kth%20Largest%20Element%20in%20an%20Array%20-%20Leetcode%20215/Kth%20Largest%20Element%20in%20an%20Array%20-%20Leetcode%20215.py
#Last solution
def test_case_0():#PASSED 
    int_0 = 785
    list_0 = [int_0, int_0]
    bool_0 = True
    int_1 = module_0.findKthLargest(list_0, bool_0)
    assert int_1 == 785
    int_2 = module_0.findKthLargest(list_0, int_0)


# @pytest.mark.xfail(strict=True)
def test_case_1():#FAILED test_cod.py::test_case_1 - TypeError: 'float' object is not iterable
    float_0 = 3429.0
    set_0 = set()
    module_0.findKthLargest(float_0, set_0)
