# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import leetcode344 as module_0


def test_case_0(): #PASSED
    str_0 = "Wi"
    str_1 = "v\x0c\r T>\\'Or\"xl4v=)NP~"
    list_0 = [str_0, str_1]
    solution_0 = module_0.Solution()
    none_type_0 = solution_0.reverseString(list_0)


def test_case_1(): #PASSED
    str_0 = "-b"
    list_0 = [str_0]
    solution_0 = module_0.Solution()
    str_1 = "5~o\r@f\rVD\tAb&Ux"
    list_1 = [str_1]
    none_type_0 = solution_0.reverseString(list_1)
    dict_0 = {}
    solution_1 = module_0.Solution()
    solution_2 = module_0.Solution(**dict_0)
    none_type_1 = solution_2.reverseString(list_0)


#@pytest.mark.xfail(strict=True)
def test_case_2(): #FAILED test_leetcode_344.py::test_case_2 - TypeError: object of type 'Solution' has no len()
    str_0 = "K-\t*"
    str_1 = "`$N*k \x0bSZK\r"
    str_2 = "RP9x\\=R1jqT<*@CT.L;"
    str_3 = "IIg>at4\nIsT1w\nY$[j/{"
    list_0 = [str_0, str_1, str_2, str_3]
    solution_0 = module_0.Solution()
    none_type_0 = solution_0.reverseString(list_0)
    list_1 = []
    solution_1 = module_0.Solution()
    none_type_1 = solution_1.reverseString(list_1)
    solution_2 = module_0.Solution()
    solution_1.reverseString(solution_1)
