# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P2 as module_0


def test_case_0():
    bool_0 = True
    bool_1 = False
    list_0 = [bool_0, bool_1, bool_0]
    solution_0 = module_0.Solution()
    bool_2 = solution_0.containsDuplicate(list_0)
    assert bool_2 is True


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    solution_0 = module_0.Solution()
    bool_0 = solution_0.containsDuplicate(list_0)
    solution_1 = module_0.Solution()
    str_0 = "AYRygP,M?>5y!"
    solution_2 = module_0.Solution()
    solution_3 = module_0.Solution()
    module_0.Solution(**str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "hr>iu3rMd&z"
    none_type_0 = None
    dict_0 = {str_0: none_type_0}
    module_0.Solution(**dict_0)
