# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import RemoveNthNodefromEndofList as module_0


#@pytest.mark.xfail(strict=True)
def test_case_0():#FAILED: 'str' object has no attribute 'next'
    str_0 = "eCWGpH~g2"
    int_0 = 6328
    module_0.removeNthFromEnd(str_0, int_0)


#@pytest.mark.xfail(strict=True)
def test_case_1():#FAILED: 'NoneType' object has no attribute 'next'
    none_type_0 = None
    list_node_0 = module_0.ListNode()
    assert list_node_0.val == 0
    list_node_1 = module_0.ListNode()
    assert list_node_1.val == 0
    bool_0 = False
    module_0.removeNthFromEnd(none_type_0, bool_0)


#@pytest.mark.xfail(strict=True)
def test_case_2():#FAILED: 'NoneType' object has no attribute 'next'
    list_node_0 = module_0.ListNode()
    assert list_node_0.val == 0
    bool_0 = False
    module_0.removeNthFromEnd(list_node_0, bool_0)


#@pytest.mark.xfail(strict=True)
def test_case_3(): #FAILED: 'bytes' object has no attribute 'next'
    bytes_0 = b"!"
    int_0 = -387
    list_node_0 = module_0.ListNode(next=bytes_0)
    assert list_node_0.val == 0
    module_0.removeNthFromEnd(bytes_0, int_0)
