# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P9 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
    var_0 = solution_0.majorityElement(list_0)
    assert var_0 == -1
    solution_0.majorityElement(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 409
    list_0 = [int_0, int_0]
    module_0.Solution(*list_0)


def test_case_2():
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
    var_0 = solution_0.majorityElement(list_0)
    assert var_0 == -1
    dict_0 = {solution_0: list_0}
    var_1 = solution_0.majorityElement(dict_0)
    assert f"{type(var_1).__module__}.{type(var_1).__qualname__}" == "C2P9.Solution"


def test_case_3():
    none_type_0 = None
    solution_0 = module_0.Solution()
    str_0 = "ZhV\tcFC\x0b"
    list_0 = [none_type_0, str_0, solution_0]
    var_0 = solution_0.majorityElement(list_0)
    var_1 = solution_0.majorityElement(str_0)
    assert var_1 == "Z"


@pytest.mark.xfail(strict=True)
def test_case_4():
    solution_0 = module_0.Solution()
    str_0 = "Zhh\tcFC\x0b"
    var_0 = solution_0.majorityElement(str_0)
    assert var_0 == "h"
    solution_0.majorityElement(solution_0)
