# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import max_cons as module_0


def test_case_0(): # PASSED
    solution_0 = module_0.Solution()
    bool_0 = True
    list_0 = [bool_0]
    int_0 = solution_0.longestOnes(list_0, bool_0)
    assert int_0 == 1


def test_case_1(): # PASSED
    solution_0 = module_0.Solution()
    solution_1 = module_0.Solution()


# @pytest.mark.xfail(strict=True)
def test_case_2(): # FAILED - TypeError: '>' not supported between instances of 'int' and 'list'
    solution_0 = module_0.Solution()
    bool_0 = False
    bool_1 = False
    int_0 = 2217
    list_0 = [bool_0, bool_0, bool_1, int_0]
    solution_0.longestOnes(list_0, list_0)


# @pytest.mark.xfail(strict=True)
def test_case_3(): # FAILED - IndexError: string index out of range
    list_0 = []
    int_0 = -1920
    str_0 = "+@WO5*{&=*%\x0c;*j2`4U"
    solution_0 = module_0.Solution(*list_0)
    solution_0.longestOnes(str_0, int_0)


def test_case_4(): # PASSED
    bool_0 = False
    list_0 = [bool_0]
    solution_0 = module_0.Solution()
    int_0 = solution_0.longestOnes(list_0, bool_0)
    assert int_0 == 0
    int_1 = 2714
    bool_1 = False
    list_1 = [bool_0, int_1, bool_1]
    int_2 = solution_0.longestOnes(list_1, bool_0)
    assert int_2 == 1
