# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import tests.C1P5 as module_0


def test_case_0():
    int_0 = -1324
    list_0 = [int_0]
    solution_0 = module_0.Solution()
    int_1 = solution_0.maxProfit(list_0)
    assert int_1 == 0
    int_2 = solution_0.maxProfit(list_0)
    assert int_2 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.maxProfit(list_0)
    assert int_0 == 0
    module_0.Solution(*list_0, **list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.Solution(**none_type_0)
