# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import leetcode977 as module_0


#@pytest.mark.xfail(strict=True)
def test_case_0(): #FAILED test_main.py::test_case_0 - TypeError: 'bytes' object does not support item assignment
    bytes_0 = b"\xce\xad"
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
    solution_0.sortedSquares(bytes_0)


def test_case_1(): #PASSED
    list_0 = []
    solution_0 = module_0.Solution()
    list_1 = solution_0.sortedSquares(list_0)
    solution_1 = module_0.Solution()


#@pytest.mark.xfail(strict=True)
def test_case_2(): #FAILED test_main.py::test_case_2 - TypeError: Solution() takes no arguments
    str_0 = "l)"
    solution_0 = module_0.Solution()
    int_0 = -1206
    list_0 = [int_0, int_0, int_0, int_0]
    list_1 = solution_0.sortedSquares(list_0)
    dict_0 = {str_0: str_0, str_0: str_0}
    module_0.Solution(**dict_0)


#@pytest.mark.xfail(strict=True)
def test_case_3(): #FAILED test_main.py::test_case_3 - TypeError: main.Solution() argument after ** must be a mapping, not list
    dict_0 = {}
    int_0 = -2797
    bool_0 = False
    bool_1 = True
    list_0 = [int_0, bool_0, bool_0, bool_1]
    solution_0 = module_0.Solution()
    list_1 = solution_0.sortedSquares(list_0)
    solution_1 = module_0.Solution()
    list_2 = solution_1.sortedSquares(dict_0)
    int_1 = -269
    list_3 = [int_1, int_1]
    solution_2 = module_0.Solution()
    solution_3 = module_0.Solution()
    module_0.Solution(**list_3)
