# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P4 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    solution_0 = module_0.Solution()
    str_0 = " ,yB(3_:|d|Rb"
    bool_0 = solution_0.isAnagram(str_0, str_0)
    assert bool_0 is True
    solution_1 = module_0.Solution()
    str_1 = 'O%zVZu"DeF'
    bool_1 = solution_0.isAnagram(str_1, str_0)
    solution_2 = module_0.Solution()
    solution_2.isAnagram(solution_1, solution_1)


def test_case_1():
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
