# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import cod as module_0
#https://github.com/gahogg/Leetcode-Solutions/blob/main/Subsets%20-%20Leetcode%2078/Subsets%20-%20Leetcode%2078.py

@pytest.mark.xfail(strict=True)
def test_case_0():#XFAIL   #FAILED test_cod.py::test_case_0 - TypeError: subsets() missing 1 required positional argument: 'nums'
    list_0 = []
    module_0.subsets(list_0)
