# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import tests.C1P3 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "n3g\x0bEIoSqf+7"
    bytes_0 = b""
    solution_0 = module_0.Solution(*bytes_0)
    solution_0.romanToInt(str_0)


def test_case_1():
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.romanToInt(list_0)
    assert int_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "%"
    solution_0 = module_0.Solution()
    solution_0.romanToInt(str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "D"
    solution_0 = module_0.Solution()
    int_0 = solution_0.romanToInt(str_0)
    assert int_0 == 500
    solution_0.romanToInt(solution_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    solution_0 = module_0.Solution()
    str_0 = ""
    int_0 = solution_0.romanToInt(str_0)
    assert int_0 == 0
    str_1 = "CCD"
    int_1 = solution_0.romanToInt(str_1)
    assert int_1 == 500
    list_0 = [str_0, int_1]
    module_0.Solution(*list_0)
