# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import tests.C1P1 as module_0



@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "UhP+AZbrN_"
    solution_0 = module_0.Solution()
    solution_0.findClosestNumber(str_0)


def test_case_1():
    int_0 = 1614
    list_0 = [int_0, int_0]
    list_1 = []
    solution_0 = module_0.Solution()
    solution_1 = module_0.Solution(*list_1)
    int_1 = solution_1.findClosestNumber(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    solution_0 = module_0.Solution()
    solution_1 = module_0.Solution()
    solution_1.findClosestNumber(list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    int_0 = 375
    bool_0 = False
    list_0 = [int_0, bool_0, int_0, int_0]
    solution_0 = module_0.Solution()
    int_1 = solution_0.findClosestNumber(list_0)
    assert int_1 is False
    solution_1 = module_0.Solution()
    dict_0 = {}
    module_0.Solution(*none_type_0, **dict_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    solution_0 = module_0.Solution()
    int_0 = -798
    list_0 = [int_0, int_0]
    int_1 = solution_0.findClosestNumber(list_0)
    assert int_1 == -798
    list_1 = []
    solution_0.findClosestNumber(list_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    solution_0 = module_0.Solution()
    bool_0 = True
    bool_1 = False
    int_0 = 955
    int_1 = -1
    list_0 = [int_1, bool_0, int_0]
    int_2 = solution_0.findClosestNumber(list_0)
    assert int_2 == 1
    int_3 = solution_0.findClosestNumber(list_0)
    assert int_3 == 1
    list_1 = [bool_0, bool_0, bool_0, int_1, bool_1, int_0]
    int_4 = solution_0.findClosestNumber(list_1)
    assert int_4 is False
    list_2 = [bool_0, int_0, bool_0, bool_0]
    solution_1 = module_0.Solution()
    solution_2 = module_0.Solution()
    int_5 = solution_2.findClosestNumber(list_2)
    assert int_5 is True
    solution_1.findClosestNumber(solution_1)
