# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import leetcode739 as module_0


def test_case_0(): #PASSED
    int_0 = -647
    bool_0 = True
    int_1 = 1728
    list_0 = [int_0, bool_0, bool_0, int_1]
    solution_0 = module_0.Solution()
    list_1 = solution_0.dailyTemperatures(list_0)


def test_case_1(): #PASSED
    solution_0 = module_0.Solution()


def test_case_2(): #PASSED
    int_0 = 2375
    bool_0 = False
    int_1 = 1184
    int_2 = 1039
    list_0 = [int_0, bool_0, int_1, int_2]
    solution_0 = module_0.Solution()
    list_1 = solution_0.dailyTemperatures(list_0)
    dict_0 = {}
    solution_1 = module_0.Solution()
    solution_2 = module_0.Solution(**dict_0)