# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import leetcode42 as module_0


def test_case_0(): #PASSED
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.trap(list_0)
    assert int_0 == 0
    int_1 = -2971
    list_1 = [int_1, int_1, int_1]
    solution_1 = module_0.Solution()
    int_2 = solution_1.trap(list_1)
    assert int_2 == 8913
    int_3 = solution_1.trap(list_1)
    assert int_3 == 8913


def test_case_1(): #PASSED
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.trap(list_0)
    assert int_0 == 0