# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import cod as module_0
#https://github.com/gahogg/Leetcode-Solutions/blob/main/Top%20K%20Frequent%20Elements%20-%20Leetcode%20347/Top%20K%20Frequent%20Elements%20-%20Leetcode%20347.py
#Last solution
def test_case_0():#PASSED 
    list_0 = []
    list_1 = module_0.topKFrequent(list_0, list_0)


def test_case_1():#PASSED 
    int_0 = 48
    list_0 = [int_0]
    list_1 = module_0.topKFrequent(list_0, int_0)


def test_case_2():#PASSED 
    bool_0 = False
    bool_1 = True
    list_0 = [bool_0, bool_0, bool_1]
    list_1 = module_0.topKFrequent(list_0, bool_1)


def test_case_3():#PASSED 
    int_0 = 151
    bool_0 = True
    bool_1 = True
    list_0 = [int_0, int_0, bool_0, bool_1]
    list_1 = module_0.topKFrequent(list_0, bool_0)
    bool_2 = False
    list_2 = [bool_2, bool_2, bool_2]
    list_3 = module_0.topKFrequent(list_2, bool_2)
