# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import cod as module_0


def test_case_0():
    bool_0 = False
    int_0 = -2033
    list_0 = [bool_0, int_0]
    list_1 = [list_0]
    list_2 = module_0.kClosest(list_1, int_0)


def test_case_1():
    int_0 = -2629
    bool_0 = True
    list_0 = [int_0, bool_0]
    list_1 = [list_0, list_0, list_0, list_0]
    bool_1 = True
    list_2 = module_0.kClosest(list_1, bool_1)
    list_3 = module_0.kClosest(list_1, bool_1)
