# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P6 as module_0


def test_case_0():
    float_0 = 559.102211
    set_0 = {float_0}
    dict_0 = {}
    solution_0 = module_0.Solution(**dict_0)
    list_0 = solution_0.twoSum(set_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    int_0 = 2724
    solution_0 = module_0.Solution()
    solution_0.twoSum(none_type_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    solution_0 = module_0.Solution()
    int_0 = -857
    solution_1 = module_0.Solution()
    bool_0 = False
    int_1 = 1553
    list_0 = [bool_0, bool_0, int_1]
    list_1 = solution_1.twoSum(list_0, int_1)
    solution_0.twoSum(solution_0, int_0)
