# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import C2P3 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "@Wimwm9/Rp"
    str_1 = "~Wn+_j)Iu:0\\*-wx_o"
    str_2 = "\t%-,L5\r!smI \x0bd$Av0"
    solution_0 = module_0.Solution()
    bool_0 = solution_0.canConstruct(str_1, str_2)
    assert bool_0 is False
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    list_0 = [str_1, dict_0]
    module_0.Solution(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    solution_0 = module_0.Solution()
    str_0 = "K@xgeI*>."
    bool_0 = solution_0.canConstruct(str_0, str_0)
    assert bool_0 is True
    bool_1 = solution_0.canConstruct(str_0, str_0)
    assert bool_1 is True
    bool_2 = solution_0.canConstruct(str_0, str_0)
    assert bool_2 is True
    solution_0.canConstruct(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    module_0.Solution(*list_0, **list_0)
